---
collections:
  - name: ansible.controller
  - name: ansible.posix
  - name: ansible.windows
  - name: ansible_ssa.general
  - name: community.crypto
  - name: community.general
  - name: containers.podman
  - name: freeipa.ansible_freeipa
  - name: community.vmware
    #  - name: vmware.vmware_rest
  - name: mschreie.bcl

