---
- name: Add esxi hosts to vcenter
  hosts: esx_hosts
  gather_facts: false

  tasks:
    - name: Add esxi hosts to vcenter
      ansible.builtin.include_role:
        name: portfoliossa.bcl.add_esxi_to_vcenter
      vars:
        vcenter_hostname: "{{ bclvmw_host }}"
        vcenter_username: "{{ bclvmw_username }}"
        vcenter_password: "{{ bclvmw_password }}"
        vcenter_validate_certs: "{{ bclvmw_validate_certs }}"
        vcenter_datacentername: "{{ bclvmw_datacentername }}"
        vcenter_clustername: "{{ bclvmw_clustername }}"
        esxi_hostname: "{{ host_ip }}"
        esxi_username: "root"
        esxi_password: "{{ esxi_rootpw }}"
      when: bclvmw_enable | default('false') | bool

