---
- name: create controller instance locally
  gather_facts: false
  hosts:
  - localhost

  tasks:
    - name: deploy Red Hat Ansible Automation Platform automation controller without private automation hub
      ansible.builtin.include_role:
        name: ansible_ssa.general.instance
      vars:
        instance_name: "{{ controller_instance_name }}"
        instance_group: "controller"
        instance_parameters: "{{ controller_instance_parameters | default ({}) }}"
      when: not controller_ah_enable | default ('false') | bool

    - name: deploy Red Hat Ansible Automation Platform automation controller with private automation hub
      ansible.builtin.include_role:
        name: ansible_ssa.general.instance
      vars:
        instance_name: "{{ controller_instance_name }}"
        instance_group: "controller"
        instance_additional_port: 5432
        instance_parameters: "{{ controller_instance_parameters | default ({}) }}"
      when: controller_ah_enable | default ('false') | bool

    - name: deploy private automation hub
      ansible.builtin.include_role:
        name: ansible_ssa.general.instance
      vars:
        instance_name: "{{ controller_ah_instance_name }}"
        instance_group: "automation_hub"
        instance_parameters: "{{ controller_ah_instance_parameters | default ({}) }}"
      when: controller_ah_enable | default ('false') | bool

- name: test connection to automation hub
  hosts:
    - automation_hub
  gather_facts: false
  tasks:
    - name: test SSH connection
      ansible.builtin.wait_for_connection:
        timeout: 300
      when:
        - not remove | default ('false') | bool
        - controller_ah_enable | default ('false') | bool

- name: test connection to automation controller
  hosts:
    - controller
  gather_facts: false
  tasks:
    - name: test SSH connection
      ansible.builtin.wait_for_connection:
        timeout: 300
      when: not remove | default('false') | bool
