---
- hosts: vcenter
  gather_facts: false

  collections:
    - vmware.vmware_rest
    - community.vmware

  tasks:
  - name: Build a list of all the folders
    vmware.vmware_rest.vcenter_folder_info:
      vcenter_hostname: "{{ bclvmw_host }}"
      vcenter_username: "{{ bclvmw_username }}"
      vcenter_password: "{{ bclvmw_password }}"
      vcenter_validate_certs: "{{ bclvmw_validate_certs }}"
    register: my_folders
    delegate_to: localhost

  - name: print folders found
    debug:
      var: my_folders

  - name: Assure to have a Datacenter
    vmware.vmware_rest.vcenter_datacenter:
      vcenter_hostname: "{{ bclvmw_host }}"
      vcenter_username: "{{ bclvmw_username }}"
      vcenter_password: "{{ bclvmw_password }}"
      vcenter_validate_certs: "{{ bclvmw_validate_certs }}"

      state: present
      name: '{{ bclvmw_datacentername }}'
      folder: 'group-d1'
    delegate_to: localhost


  - name: Create a folders in our datacenter
    community.vmware.vcenter_folder:
      hostname: "{{ bclvmw_host }}"
      username: "{{ bclvmw_username }}"
      password: "{{ bclvmw_password }}"
      validate_certs: "{{ bclvmw_validate_certs }}"
      datacenter_name: '{{ bclvmw_datacentername }}'
      folder_name: "{{ item.name }}"
      folder_type: "{{ item.type }}"
      state: present
    delegate_to: localhost
    loop:
       - name: vms
         type: vm
       - name: hosts
         type: host
       - name: networks
         type: network

  - name: Provide information about vCenter folders
    community.vmware.vmware_folder_info:
      hostname: "{{ bclvmw_host }}"
      username: "{{ bclvmw_username }}"
      password: "{{ bclvmw_password }}"
      validate_certs: "{{ bclvmw_validate_certs }}"
      datacenter: '{{ bclvmw_datacentername }}'
    delegate_to: localhost
    register: vcenter_folder_info

  - name: print community info about folders
    debug: 
      var: vcenter_folder_info



- hosts: esx_hosts
  gather_facts: false

  tasks:
##  - name: Connect the host(s)
##    vmware.vmware_rest.vcenter_host:
##      vcenter_hostname: "{{ bclvmw_host }}"
##      vcenter_username: "{{ bclvmw_username }}"
##      vcenter_password: "{{ bclvmw_password }}"
##      vcenter_validate_certs: "{{ bclvmw_validate_certs }}"
##
##      hostname: "{{ host_ip  }}"
##      user_name: "root"
##      password: "{{ esxi_rootpw }}"
##      thumbprint_verification: NONE
##      folder: "/{{ bclvmw_datacentername }}/host/hosts"
##    delegate_to: localhost

  - name: Connect the host(s)
    community.vmware.vmware_host:
      hostname: "{{ bclvmw_host }}"
      username: "{{ bclvmw_username }}"
      password: "{{ bclvmw_password }}"
      validate_certs: "{{ bclvmw_validate_certs }}"

      esxi_hostname: "{{ host_ip  }}"
      esxi_username: "root"
      esxi_password: "{{ esxi_rootpw }}"
      fetch_ssl_thumbprint: false
      datacenter_name: "bcl"
      folder: "/{{ bclvmw_datacentername }}/host/hosts"
        ## folder: "host/hosts"
    delegate_to: localhost

