---
- name: final config of ESXi hosts
  hosts: esx_hosts
  gather_facts: false

  tasks:
    - name: Configure NTP servers for an ESXi Host
      community.vmware.vmware_host_ntp:
        hostname: "{{ bclvmw_host }}"
        username: "{{ bclvmw_username }}"
        password: "{{ bclvmw_password }}"
        validate_certs: "{{ bclvmw_validate_certs }}"
        esxi_hostname: "{{ host_ip }}"
        ntp_servers:
          - 10.6.55.4
      delegate_to: localhost
      when:
       - not remove | default ('false') | bool

    - name: Start ntpd service setting for all ESXi Host in given Cluster
      community.vmware.vmware_host_service_manager:
        hostname: "{{ bclvmw_host }}"
        username: "{{ bclvmw_username }}"
        password: "{{ bclvmw_password }}"
        validate_certs: "{{ bclvmw_validate_certs }}"
        cluster_name: "{{ bclvmw_clustername }}"
        service_name: ntpd
        state: start
        service_policy: 'on'
      delegate_to: localhost
      run_once: true
      when:
       - not remove | default ('false') | bool

    - name: Add Host to dVS
      community.vmware.vmware_dvs_host:
        hostname: "{{ bclvmw_host }}"
        username: "{{ bclvmw_username }}"
        password: "{{ bclvmw_password }}"
        validate_certs: "{{ bclvmw_validate_certs }}"
        esxi_hostname: "{{ host_ip }}"
        switch_name: "{{ bclvmw_vswitchname }}"
        vmnics:
          - vmnic0
        state: present
      delegate_to: localhost
      throttle: 1 # this configure the task so it runs without concurrency as vCenter API doesn't like that
      when:
       - not remove | default ('false') | bool

##################
## Next task fail in all hosts with following meesage:
## fatal: [rh-bctl-1-gen9 -> localhost]: FAILED! => {"changed": false, "msg": "An error occurred while communicating with the remote host."}
##################

    - name: Enable vMotion, Management and vSAN traffic on all vmkernel adapters of the cluster
      community.vmware.vmware_vmkernel:
        hostname: "{{ bclvmw_host }}"
        username: "{{ bclvmw_username }}"
        password: "{{ bclvmw_password }}"
        validate_certs: "{{ bclvmw_validate_certs }}"
        esxi_hostname: "{{ host_ip }}"
        dvswitch_name: "{{ bclvmw_vswitchname }}"
        portgroup_name: "{{ bclvmw_portgroupname }}"
        state: present
        device: vmk0
        enable_vmotion: true
        enable_mgmt: true
        enable_vsan: true
        network:
          ip_address: "{{ host_ip }}"
          type: static
          subnet_mask: 255.255.255.0
      delegate_to: localhost
      when:
       - not remove | default ('false') | bool

    - name: Enable DRS
      community.vmware.vmware_cluster_drs:
        hostname: "{{ bclvmw_host }}"
        username: "{{ bclvmw_username }}"
        password: "{{ bclvmw_password }}"
        validate_certs: "{{ bclvmw_validate_certs }}"
        datacenter_name: "{{ bclvmw_datacentername }}"
        cluster_name: "{{ bclvmw_clustername }}"
        drs_default_vm_behavior: fullyAutomated
        enable: true
      delegate_to: localhost
      run_once: true
      when:
       - not remove | default ('false') | bool

   # - name: Enable vSAN and claim storage automatically
   #   community.vmware.vmware_cluster_vsan:
   #     hostname: "{{ bclvmw_host }}"
   #     username: "{{ bclvmw_username }}"
   #     password: "{{ bclvmw_password }}"
   #     validate_certs: "{{ bclvmw_validate_certs }}"
   #     datacenter_name: "{{ bclvmw_datacentername }}"
   #     cluster_name: "{{ bclvmw_clustername }}"
   #     enable: true
   #     vsan_auto_claim_storage: true
   #   delegate_to: localhost
   #   run_once: true
   #   when:
   #    - not remove | default ('false') | bool

###      when: bclvmw_enable | default('false') | bool
