---
- name: install dhcpd
  ansible.builtin.yum:
    name: dhcp-server
    state: present

# - name: configure dhcpd

- name: start dhcpd
  ansible.builtin.systemd:
    name: dhcpd
    state: started
    enabled: true
