---
- name: install named
  ansible.builtin.yum:
    name: 
      - bind-chroot
      - bind-utils
      - python3-dns
    state: present

- name: define serial number
  ansible.builtin.set_fact: 
  # this creates new/higher serial every 15 minutes
     serial:  "{{ ansible_date_time.year }}{{ ansible_date_time.month }}{{ ansible_date_time.day }}{{  (((ansible_date_time.hour|int) * 60 + (ansible_date_time.minute|int)) // 14.40)|int }}"

- name: configure named.conf
  ansible.builtin.template:
    src: named.conf.j2  
    dest: /etc/named.conf
    group: named
    setype: named_conf_t
    mode: 0640

- name: provide initial zone files
  ansible.builtin.template:
    src: zone.j2
    dest: /var/named/{{ item }}.zone
  loop: "{{ bastion_named_zones }}"

- name: provide initial zone files
  ansible.builtin.template:
    src: reverse_zone.j2  
    dest: /var/named/{{ item }}.zone
  loop: "{{ bastion_named_revzones }}"

- name: start named
  ansible.builtin.systemd:
    name: named
    state: restarted
    enabled: true
